name: Youtube Bot

on:
  workflow_dispatch:
    schedule:
      - cron: "0 */6 * * *"

env: 
  token: ${{ secrets.token }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup Env
         run: |
              sudo bash setup.sh
       - name: Run Bot
         run: |
              python main.py